# ---
# deployment:
#   tasks:
#     - export DEPLOY_PATH=/home/r03i4jq9fzw3/public_html
#     - npm install
#     - npm run build
#     - /bin/cp -R build/* $DEPLOY_PATH
    
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/r03i4jq9fzw3/public_html/
    - /bin/cp -r public/* $DEPLOYPATH
